# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Identifica a imaxe/box de vagrant que vas utilizar: "ubuntu/focal64"
    config.vm.box = "ubuntu/focal64"
  
    # Crea unha rede privada, que permite acceso host-only á máquina
    config.vm.network "private_network", ip: "192.168.33.20"
 
     # Indica o nome da máquina virtual
     config.vm.provider :virtualbox do |vb|
      vb.name = "mariadb-employees"
   end
  
    # Indica o nome do hostname
    config.vm.hostname = "mariadb-employees"

    config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    # servidor Bases de Datos MariaDB
    apt-get install -y mariadb-server

    sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf     
    sudo mariadb -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' IDENTIFIED BY 'password';"
    systemctl restart mariadb.service

    # carga de base de datos
    git clone https://github.com/datacharmer/test_db.git
    cd test_db
    mariadb < employees.sql

   SHELL

  end