# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Identifica a imaxe/box de vagrant que vas utilizar: "ubuntu/focal64"
    config.vm.box = "ubuntu/focal64"

    config.vm.boot_timeout = 1200
  
    # Indica o nome da máquina virtual
    config.vm.provider :virtualbox do |vb|
      vb.name = "host4windows"
      vb.memory = 8192
      vb.cpus = 4
    end
 
    
    config.vm.provision "shell", inline: <<-SHELL
    
    apt update
    apt install figlet

    SHELL

    # Indica o nome do hostname
    config.vm.hostname = "host4windows"

    config.vm.network "forwarded_port", guest: 22, host: 22222
  

  end
