# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Identifica a imaxe/box de vagrant que vas utilizar: "ubuntu/focal64"
    config.vm.box = "ubuntu/focal64"

    # Crea unha rede privada, que permite acceso host-only á máquina
    config.vm.network "private_network", ip: "192.168.33.150"

    # comparte a carpeta con datos para crear a BD
    config.vm.synced_folder "./data", "/vagrant_data"

     # Indica o nome da máquina virtual
     config.vm.provider :virtualbox do |vb|
      vb.name = "practica-sql"
   end

    # Indica o nome do hostname
    config.vm.hostname = "practica-sql"

    config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    # servidor Bases de Datos MariaDB
    apt-get install -y mariadb-server

    sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
    sudo mariadb -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' IDENTIFIED BY 'password';"
    systemctl restart mariadb.service

    # carga de base de datos
    cd /vagrant_data
    mariadb < creacion_base_de_datos.sql
    mariadb < carga_de_datos_universidade.sql

   SHELL

  end
