Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.define "hadoop-master" do |config|
    config.vm.network :private_network, ip:"192.168.33.11"
    config.vm.hostname = "hadoop-master"
    config.vm.provision :shell, path: "scripts/1_download_and_install_hadoop.sh"
    config.vm.provision :shell, path: "scripts/2_run_master.sh"
    config.vm.provision :shell, path: "scripts/3_run_worker.sh"
    config.vm.provision :shell, path: "scripts/4_download_and_install_pig.sh"
  end


end
